### ISSUE TITLE
colPos dropdown list presents option from Page Layout - subpages instead of current layout

### ISSUE THREAD

**Issue by ilomedia** [FluidTYPO3/fluidpages#388] opened 2018-10-07 14:19 UTC
Hi all,

TYPO3 8.7.19, i just updated from flux, fluidcontent, fluidpages to flux 9.1, fluidpages 4.3 and i have a weird behaviour with columns. It is quite an old but well maintained project.

the problem is : on any page, when i edit a content, the column dropdown only proposes columns from subpage controller instead of current page controller. If i set the same template as tx_fed_page_controller_action_sub i have the right columns, but of course it is not the expected behaviour.

I do have a nameSpaced provider extension, registerProviderExtensionKey is set in ext_localconf.php, i ran flux update script succesfully (after i fixed colPos for my contents).

Even weirder, my layout is OK in page mode, only when i edit a content i have [INVALID VALUE (51)] in the colPos dropdown (since this colPos does not exist in the sub template).

To check if the problem does not come from my code i disabled my extension and tried https://github.com/FluidTYPO3/flux/files/2197422/test-provider-extension.zip and i have the exact same behaviour : 

- if i set "Page Layout" but no "Page Layout - subpages" i have the default TYPO3 columns in the dropdown list (Left, Normal, Right, Border) instead of the template columns
- i get "Main content", "Side content" only if i also set "Page Layout - subpages" as same template

I cleared the cache from install tool, deleted typo3temp/var, nothing works :(

values from pages table : 
backend_layout : fluidpages__grid
backend_layout_next_level : fluidpages__grid
tx_fed_page_controller_action : Test.Testing.standard
tx_fed_page_controller_action_sub : Test.Testing.standard (or empty depending on test)

**EDIT** : This is going insane, i tried to uninstall testing extension and reinstall my extension and it does not work anymore with backend layouts, the dropdown list only proposes None and FluidTypo3.Flux as if my provider extension was not set.

If this is a cache or loading order problem, how could i fix this? (i cleared cache from install tool and my ext depends on flux and fluidpages)

**EDIT2** : after a lot of tests i managed to get my backend layouts drowpdown list back to normal (instead of being stuck to None/FluidTypo3.Flux), indeed i first selected a page layout, which forced the form to reload and then my backend layouts where available in the dropdown list, this trick might be useful to others.

Nervertheless, i still got the bug for columns in contents.

**Comment by ilomedia** [comment] 2018-10-07 20:14
after a long but interesting search i feel that the problem lies in FluidTYPO3\Flux\Provider\resolveConfigurationProviders and has something to do with either :
- the way priorities are handled (all priorities are 50, normal?)
- the fact that SubPageProvider should not be last in the list of provider

anyway this seems to be a Flux problem, should we close here and open an issue in Flux?

**Comment by ilomedia** [comment] 2018-10-10 09:50
I can confirm the problem with a fresh TYPO3 8.7.19 install, steps to reproduce : 

- install TYPO3 as tar.gz
- create a home page and a sub page
- install flux and fluidpages
- install testing extension (with offending content deleted)
- add a Home.html in Templates/Page with a new column
- add according labels to locallang.xlf
- Select "Test.Testing" for "Backend Layout (this page only)" and "Backend Layout (subpages of this page) " 
- select "Home" template for "Page Layout - this page" field and "Example Page" for "Page Layout - subpages"

> when you edit content on the home page only the 2 columns from Example Page are proposed

**Comment by NamelessCoder** [comment] 2018-10-10 10:09
I'm a little short on time but perhaps you can find the next step by looking into https://github.com/FluidTYPO3/flux/blob/development/Classes/Form/Container/Grid.php#L122 which is where the Grid gets processed to extract allowed colPos values. The instance that resolves should as far as I understand your use case be coming from the main (not sub) Provider instance and should contain an "options" property with one option being the template filename you selected in main action.

Re: priorities, the intention is that the two providers are separated by field name - not by priority. One provider should only react to the sub-field name (but will traverse the page root line to find a value) whereas the other should not trigger at all unless you really make a selection in "Page layout - this page". But you may be onto something here because it's possible that when resolving the provider, *no field name gets used which means both providers apply and whichever returns TRUE from trigger() first, is the one that gets used*. If this is the case then raising the priority of the **main** provider (by overriding the property or getter method for priority) might also solve your problem. It's worth checking out and trying.

**Comment by ilomedia** [comment] 2018-10-10 13:57
No problem, thanks for taking my problem into account.

I tried to raise and lower priority for PageProvider to 60 and 40 : no luck

Nevertheless i don't think that the problem lies in https://github.com/FluidTYPO3/flux/blob/development/Classes/Form/Container/Grid.php#L122 since in https://github.com/FluidTYPO3/flux/blob/development/Classes/Integration/Overrides/BackendLayoutView.php#L68 $pageLevelProvider is already an instance of FluidTYPO3\Fluidpages\Provider\SubPageProvider where it should be FluidTYPO3\Fluidpages\Provider\PageProvider

**Comment by ilomedia** [comment] 2018-10-10 14:10
I just added the following code
```
foreach($providers as $provider) {
            echo(get_class($provider)).'
';
        }
```
right after https://github.com/FluidTYPO3/flux/blob/development/Classes/Provider/ProviderResolver.php#L76 and the result is 
```
FluidTYPO3\Fluidpages\Provider\PageProvider
FluidTYPO3\Fluidpages\Provider\SubPageProvider
```
and since you use the last element in array as primary provider, SubPage is used instead of Page.
It is weird though that playing with priority does not have any effect

**Comment by ilomedia** [comment] 2018-10-10 14:29
Feeling stupid : 
FluidTYPO3\Fluidpages\Provider\SubPageProvider extends FluidTYPO3\Fluidpages\Provider\PageProvider therefore changing the value in PageProvider was pointless.

I did a new test setting PageProvider priority to 60 and SubPageProvider priority back to 50 and it works as expected for the test home page where 3 columns are proposed and also the subpage where only the 2 default columns appear.

Now my fear is with PageLanguageOverlayProvider and SubPageLanguageOverlayProvider and maybe others i'm not aware of, what priority to give them not to breaks things?

**Comment by blueamerican** [comment] 2018-10-17 10:12
is there a fix?
fluidpages is not usable without.

**Comment by netthinks** [comment] 2018-10-29 10:53
same problem here, is there a solution? Thanks!

**Comment by NamelessCoder** [comment] 2018-10-30 09:30
Oh and I should add: it is extremely acceptable if you vote 👍 on the issue to indicate you're also looking for a solution, without having to put a comment saying "I'm also experiencing this". We do look at these as a way to gauge how important issues are ;)

**Comment by grimmcreative** [comment] 2019-02-18 15:48
The Problem occurs when you just install FLUX - no fluidpages needed to reproduce.
When installing just **flux** why i want to use just **flux** for content elements not for pagetemplates the column dropdown only shows standard values. No values from any Backend Layout is shown.

**Closed** 2019-04-22 11:29 UTC

**Comment by michael-binder** [comment] 2019-09-19 09:51
Perfect, the changes in the Bugfix solves the problem.
