### ISSUE TITLE
Error when a page configuration option remains empty

### ISSUE THREAD

**Issue by Kaimane** [FluidTYPO3/fluidpages#256] opened 2015-05-08 12:27 UTC
Environment: TYPO3@6.2.12 / VHS@2.3.2 / Flux@7.2.0 / Fluidpages@3.2.2 (extensions are installed from TER)

When using fluidpages with page configuration options I get an unusual error. There is one flux:field.file control in the page template. When I choose a file for this page and the form control for the subpages remains empty I got following error message:

`#1: PHP Warning: array_values() expects parameter 1 to be array, string given in [...]/typo3_src-6.2.12/typo3/sysext/extbase/Classes/Service/FlexFormService.php line 37`

With Fluidpages@3.2.0 the error does not occur. But from version 3.2.1 of Fluidpages the error occur if form control remains empty.

**Comment by bjo3rnf** [comment] 2015-05-08 13:15
Confirmed. This is caused by an empty <data/> node in the flexform xml as it seems.

**Comment by blueamerican** [comment] 2015-05-12 06:00
i have the same error. it only appears in development environement.

**Comment by bjo3rnf** [comment] 2015-05-15 06:01
This should be fixed now by https://github.com/FluidTYPO3/flux/pull/832

**Closed** 2015-05-15 06:02 UTC

**Comment by MoppieMop** [comment] 2015-05-26 12:13
I can not confirm that this issue is fixed. Flux: 7.2.1 and FluidPages: 3.2.3 but I got the warnings from above. Cache is cleared.

**Comment by bjo3rnf** [comment] 2015-05-26 12:15
Hi @MoppieMop and @all,

unfortunately existing corrupted records have to be cleaned manually. The fix won't affect those, sorry.

Cheers
Björn

**Comment by MoppieMop** [comment] 2015-05-27 08:01
What exactly do I have to delete? The whole page? I tried to delete the flexform in the pages but this does not work.

**Comment by bjo3rnf** [comment] 2015-05-27 08:38
It's sufficient to NULL the fields ``tx_fed_page_flexform`` and ``tx_fed_page_flexform_sub`` of the affected page record. Maybe you'll also have to move up the rootline and do that for every page with an empty-to-be flexform but I'm not sure about the latter.

**Comment by MoppieMop** [comment] 2015-05-27 09:25
Ok, I got it. The problem was my menu - so a lot of pages where loaded. After I cleaned the flexform from _all_ of my pages the errors are gone. Thanks!
