### ISSUE TITLE
Fatal error:  Call to a member function message() on a non-object / PageConfigurationService missing

### ISSUE THREAD

**Issue by cweiske** [FluidTYPO3/fluidpages#308] opened 2016-01-27 09:39 UTC
With TYPO3 7.6.2, flux from git (3c5947b) and fluidpages from git (5dabf9b) I get the following error when trying to view a page in the backend:

> Fatal error: Call to a member function message() on a non-object in ../ext/fluidpages/Classes/Provider/PageProvider.php on line 192

The `pageConfigurationService` object is `NULL`; does not seem to be injected anymore.

**Comment by NamelessCoder** [comment] 2016-02-03 10:18
You may need to flush caches via the install tool. The Reflection cache is exceptionally pesky when it contains an invalidated Reflection of a class that gets used when you use the regular clear cache command.

**Comment by NamelessCoder** [comment] 2016-02-25 12:56
Will close this one as caused by reflection cache, if that's incorrect please drop me a line!

**Closed by NamelessCoder** 2016-02-25 12:56 UTC
