### ISSUE TITLE
Usage of pages_language_overlay in TYPO3 9.5

### ISSUE THREAD

**Issue by MrMooky** [FluidTYPO3/fluidpages#391] opened 2018-10-09 15:17 UTC
I noticed that fluidpages (and VHS) compatible versions for TYPO3 9 still use "pages_language_overlay" within the following places:

**fluidpages**/Classes/Provider/PageLanguageOverlayProvider.php
**fluidpages**/Configuration/TCA/Overrides/pages_language_overlay.php
**fluidpages**/Configuration/TCA/Overrides/pages.php

**vhs**/Classes/ViewHelpers/Page/LanguageMenuViewHelper.php

This (probably) causes an error with a TYPO3 9.5 installation which was updated from a working 8.7.17 install:

`There is no entry in the $TCA array for the table "pages_language_overlay". This means that the function enableFields() is called with an invalid table name as argument.`

I'm not sure if I can just rename the table names in these files, or if anything else breaks if I do so.

**Comment by MrMooky** [comment] 2018-10-09 15:32
Ok, I just edited those four files (changed `pages_language_overlay` to `pages`) and the error messages are gone. But now I have no output within the body tag. :/

**Comment by NamelessCoder** [comment] 2018-10-09 17:10
Confirmed. We will need to implement this with a version check so we use the right table on the right version - for the time being we have to keep both 8.7 and 9.5 support.

**Comment by MrMooky** [comment] 2018-10-10 06:13
Ok. Any hint regarding the empty pages? After I changed the table names, de- and re-installed both fluidpages and vhs, cleared all caches and still no output. The backend shows this now:

<img width="404" alt="screen shot 2018-10-10 at 08 07 34" src="https://user-images.githubusercontent.com/3603346/46716320-d27c7300-cc63-11e8-8d43-406751d55afb.png">

Also, see the "Unused" column name. Weird. o_O

All content elements are in the correct column, though:

<img width="183" alt="screen shot 2018-10-10 at 08 11 08" src="https://user-images.githubusercontent.com/3603346/46716380-0f486a00-cc64-11e8-9362-566753d48677.png">

Would you advise to step back to 8.7?

**Comment by NamelessCoder** [comment] 2018-10-10 09:53
Still not sure about the cause, but the value you get in `backend_layout` is definitely not the intended one. Here's a screen grab from my local 9.5 site:

![screen shot 2018-10-10 at 11 44 04](https://user-images.githubusercontent.com/2228052/46727947-f2bb2a80-cc81-11e8-855c-169a6342e454.png)

Expected: the value that you select should contain your own `Vendor.ExtensionName` formatted identity for the extension, Flux itself doesn't provide any page templates and you shouldn't be using `FluidTYPO3.Flux` as your own vendor/extension ID. It is possible the provider extension itself was incorrectly registered as if it were the Flux extension so I'd take a look at the registrations in ext_localconf.php. This has btw always been discouraged but it could be that Flux 9.x no longer allows this to happen (for various reasons, e.g. changes in the Provider classes or template resolving using less custom and more core API).

This incorrect value if selected would affect the values you get in the `colPos` field and the backend layout grid you see (including the "Unused content" column!) but not necessarily the frontend output, as that is based exclusively on the selected page template, not the backend layout.

You almost surely do not want to have `Default.html` in your template paths unless you really, truly want it to be an absolute default including Flux returning the form instance from it for any page that does not specify a template file to use.

**Comment by slowhand11** [comment] 2018-10-24 15:03
Hi there, any updates about this?

**Comment by FaraFara** [comment] 2018-12-08 11:00
Two months is gone. Any updates about this bug?

**Closed** 2019-03-04 21:16 UTC

**Comment by NamelessCoder** [comment] 2019-03-04 21:20
Closed via https://github.com/FluidTYPO3/fluidpages/commit/8d090c2a601f061c008d719b53066e35ace664f1 because the issues related to `fluidpages` are removed with that commit plus the one right before it - and https://github.com/FluidTYPO3/vhs/pull/1523 solves the one reference to `pages_language_overlay` that remained in VHS.

**Comment by fabarea** [comment] 2019-03-28 14:15
Dare I ask to issue a release (tag / TER)  which includes this change?

**Comment by NamelessCoder** [comment] 2019-03-29 10:31
@fabarea Won't be long - Flux is ready for a new release so Fluidpages follows right after.
