### ISSUE TITLE
Page- and Contenttemplates could not be overwritten

### ISSUE THREAD

**Issue by TheNaderio** [FluidTYPO3/fluidpages#370] opened 2017-11-21 15:45 UTC
flux 8.2.1
fluidpages 4.1.0
fluidcontent 5.2.0
After upgrading fom TYPO3 7.6 to 8.7.8

I had to update all my templates after the upgrade. The front and backend works fine now.
I register my providerextension and use custom page-/contenttemplates. 
Now i have to overwrite templates with an other extension.

When i use
```
plugin {
    tx_newext {
        view {
            templateRootPaths {
                10 = EXT:oldext/Resources/Private/Templates
                20 = EXT:newext/Resources/Private/Templates/oldext
            }
    }
}
```
In the folder I have created the 'Page' and 'Content'-folders.
Now when i copy my templates to the new location there happens nothing - the old template is still loaded.

In TemplateBrowser everything looks fine - the paths are set.

Any ideas?

**Comment by jmverges** [comment] 2018-03-15 10:59
I can confirm the same behaviour

**Comment by cedricziel** [comment] 2018-03-15 11:01
Do your provider extensions depend on fluidcontent and the EXT:oldext so the loading-order is correct?

**Comment by jmverges** [comment] 2018-03-15 11:08
I can confirm the same behaviour for fluidpages (dev)+ flux(dev) without fluidcontent in the middle for overlaying fluidpages in general. Had to hardcode the following in

`protected function initializeView(ViewInterface $view)
    {
        $record = $this->getRecord();
        $extensionKey = ExtensionNamingUtility::getExtensionKey($this->provider->getControllerExtensionKeyFromRecord($record));
        /** @var RenderingContextInterface $renderingContext */
        $renderingContext = $view->getRenderingContext();
        $renderingContext->getTemplatePaths()->fillDefaultsByPackageName($extensionKey);
        $renderingContext->getTemplatePaths()->setLayoutRootPaths([''/Users/jmverges/Sites/randomsite.test/build/web/typo3conf/ext/foo/Resources/Private/Extension/bar/Layouts/']);
        $renderingContext->getTemplatePaths()->setPartialRootPaths(['/Users/jmverges/Sites/randomsite.test/build/web/typo3conf/ext/foo/Resources/Private/Extension/bar/Partials/']);
        $renderingContext->setControllerAction(
            $this->provider->getControllerActionFromRecord($record)
        );
        $this->controllerContext->getRequest()->setControllerExtensionName($extensionKey);
        $this->initializeViewVariables();
        $this->initializeViewHelperVariableContainer();
        HookHandler::trigger(
            HookHandler::CONTROLLER_VIEW_INITIALIZED,
            [
                'view' => $view,
                'request' => $this->request,
                'provider' => $this->provider,
                'controller' => $this,
                'extensionKey' => $extensionKey
            ]
        );
    }`

**Comment by TheNaderio** [comment] 2018-10-18 07:35
I got the same Problem now with
* TYPO3 9.5
* Flux 9.1.0
* Fluidpages 4.3.0

I found the line (with a comment "Special temporary case"):
`$templateRootPath = ExtensionManagementUtility::extPath($legacyKey, 'Resources/Private/Templates/Content/');`

Does this mean that it is currently not possible to overwrite the paths of the Templates?

**Comment by MediKathi** [comment] 2018-10-23 11:36
I have a very similar Problem (with partials) with the current version:

https://github.com/FluidTYPO3/fluidpages/issues/389

**Comment by NamelessCoder** [comment] 2018-10-23 11:53
I'm sorry to say this but it is not possible, by design, to change those lookup paths. The reason is that the configuration you add is page-context-sensitive whereas the registrations you perform are global.

If you need to be able to perform overrides on certain pages, structure your templates so they render partials or depend on layouts that you can then override on individual pages by using TS configuration.

That being said, if the *partial* root paths you override in TS are not respected when you render in FE there might be a separate (controller-init-related) problem. I'll keep this issue open and wait for your feedback.

**Comment by MediKathi** [comment] 2018-10-23 12:14
I'm also think, that something with the controller loading went wrong.

Because changes in my PageController:

> namespace Dm\DmLayout1\Controller;
> use FluidTYPO3\Fluidpages\Controller\PageController as AbstractController;
> /**
>  * Page Controller
>  *
>  * @route off
>  */
> class PageController extends AbstractController {
> }

are ignored.

I had to hardcode the partial paths like https://github.com/FluidTYPO3/fluidpages/issues/370#issuecomment-373340195 in direct into the FluidPages PageController to make them work.

in the ext_localconf.php i use this code to register the Controller
> \FluidTYPO3\Flux\Core::registerProviderExtensionKey('Dm.DmLayout1', 'Page');

The TypoScript is also Loaded correctly (Backend Template Analysis)
> [partialRootPaths]
>
>    [0] = EXT:dm_layout/Resources/Private/Partials/
>    [1] = EXT:dm_layout1/Resources/Private/Partials/

**Comment by NamelessCoder** [comment] 2018-10-24 10:35
Just a quick note, if `dm_layout1` is your *override* which it appears it is, then the controller class name above will not be resolved as your provider extension is still registered with the original, not the override, extension identity. If anything you'd have to do this in the `dm_layout` extensions controller.

**Comment by MediKathi** [comment] 2018-10-24 10:59
the page controller is basically the same as from dm_layout1 just without the 1 in the namespace and registration.

both extensions are having the same partial paths:
[0] = EXT:dm_layout/Resources/Private/Partials/
[1] = EXT:dm_layout1/Resources/Private/Partials/

So pages from dm_layout1 are loading partials from dm_layout first, instead from dm_layout1.

Partials sould be loaded from dm_layout1 first.

**Comment by NamelessCoder** [comment] 2019-04-22 12:33
@MediKathi please continue in https://github.com/FluidTYPO3/fluidpages/issues/389 regarding the partial paths.

Closing this issue since the main topic cannot (yet) be fulfilled. I am pushing for future versions of TYPO3 to no longer declare Fluid template paths in TS but use global configuration, at which time it will be natively possible to override also templateRootPaths (for any extension, not just Flux).

**Closed by NamelessCoder** 2019-04-22 12:33 UTC
