### ISSUE TITLE
fluidpages influences page language overlay behaviour

### ISSUE THREAD

**Issue by phth** [FluidTYPO3/fluidpages#270] opened 2015-08-11 10:38 UTC
We have discovered a strange issue that happens in all of our fluidpages-based multilanguage typo3 instances (TYPO3 6.2.14, fluidpages 3.2.3):
If we use 
```typoscript
10 = TEXT
10.field = description
```
the description is not overlayed in a non-default language. 
If we use 
```typoscript
10 = TEXT
10.data = levelfield:-1, description, slide
```
everything works correct.

However, if we uninstall fluidpages, the 10.field-notation is working, too.
The Issue is also known by some other users, please see 
https://github.com/mblaschke/TYPO3-metaseo/issues/3

If you need some debugging informations i will try to provide it. 
Maybe there is something weird in my configuration, but i cannot figure it out.

**Comment by thomaszbz** [comment] 2015-08-31 19:32
Here's a test case: https://github.com/mblaschke/TYPO3-metaseo/issues/122

I can reproduce that as soon as I enable fluidpages, the metatag content is not translated in the frontend output.

Basically that means that either fluidpages or flux (which fluidpages depends on) set the language to the default language.

**Comment by NamelessCoder** [comment] 2015-09-13 12:28
I'm going to have to close this one as most likely related to configuration. Of course I checked and there is literally zero calls to `cObj` in fluidpages. Flux has a single usage: a call to build a list of enableFields, which definitely does not have the capacity to cause such a problem.

You don't mention what you use when testing this *without* fluidpages so I can only guess on possible causes, but the more likely ones are:

* Some TS is required in the global PAGE object but is set as `page.10.*` - fluidpages uses `page.5` (for a legacy reason and with TemplaVoila's uncertain fate it may, may not be required in the future).
* Extbase is used by fluidpages to render via a controller. If Extbase for whatever reason initialises the `cObj` object incorrectly that might cause your issue. It could be that Extbase doesn't know the difference between a "regular" `cObj` and a page `cObj` and doesn't set things like the list of page overlay fields.

If the problem is caused by the TS thing you can probably just duplicate whatever you set into `page.10` and also set that in `page.5`. When using fluidpages you would have a `USER` object at `page.5` so I assume that would support the same functions as whatever your alternative page renderer uses.

However, if the problem is caused by incorrect initialisation in Extbase (ConfigurationManager and/or Bootstrap, specifically Request building) then the only advise I can give is to report it to the core bug tracker, maybe submit a fix that adds the special handling of `pages` table's `cObj` instances.

Hope this helps! Please link if you report this to the core bug tracker, I'd be happy to vote and review for a solution!

**Closed by NamelessCoder** 2015-09-13 12:28 UTC

**Comment by thomaszbz** [comment] 2015-11-03 13:39
@ affected users: We're continuing further investigation at

* https://github.com/mblaschke/TYPO3-metaseo/issues/3 and
* https://github.com/mblaschke/TYPO3-metaseo/issues/122 (duplicate)

**Comment by jurajsulek** [comment] 2017-12-06 15:14
@NamelessCoder 
Sorry i know this is closed and you said it is a bug from Core but this error is still there. 
When i dissable fluidpages extension for example with "page.5 >" then everything work's fine. 
If i add in
fluidpages/Classes/Controller/PageController.php 
at the end of function initializeView()
this code: 
$GLOBALS['TSFE']->cObj->data=$GLOBALS['TSFE']->page;
then the translations works fine again. Maybe this could be a dirty fix till the error is investigated.
