### ISSUE TITLE
Drop area in empty wrapper element is missing

### ISSUE THREAD

**Issue by DenisMir** [FluidTYPO3/fluidpages#246] opened 2015-04-02 09:43 UTC
I got a fluid content wrapper element which has a `<flux:form.content name="content" />` inside. When I'm trying to drag a content element in this content area I am missing a drop area. When I add a child element the normal way (add content element icon) and try to drag & drop another second content element inside the content area everything works fine.

**Comment by coding46** [comment] 2015-04-02 10:09
I tried out your described steps but I can't reproduce the issue with CMS 6.2.* and CMS 7.1 Could you please be more verbose about your settings? A full minimal example of the templates you are using would be helpful.

**Comment by DenisMir** [comment] 2015-04-02 12:25
For sure I can give you an example. At the moment we are working with TYPO3 LTS 6.2.9 and vhs@2.2.0, flux@7.1.2, fluidpages@3.1.2 and fluidcontent@4.1.1. Each page has "Backend Layout" `fluidpages` and the page layout mentioned below selected.

Here is a simple setup:

**Layout**

```html
<f:layout name="Page" />

<div class="page__content">
  <f:render section="Main" />
</div>
```

**Page Template**

```html
<div xmlns="http://www.w3.org/1999/xhtml" lang="en"
   xmlns:v="http://typo3.org/ns/FluidTYPO3/Vhs/ViewHelpers"
   xmlns:flux="http://typo3.org/ns/FluidTYPO3/Flux/ViewHelpers"
   xmlns:f="http://typo3.org/ns/fluid/ViewHelpers">

  <f:layout name="Page" />

  <f:section name="Configuration">
    <flux:form id="oneColumnPage" icon="{f:uri.resource(path: 'Icons/Page.gif')}">
      <flux:grid>
        <flux:grid.row>
          <flux:grid.column colPos="0" name="main" />
        </flux:grid.row>
      </flux:grid>
    </flux:form>
  </f:section>

  <f:section name="Main">
    <v:content.render column="0" slide="-1" />
  </f:section>

</div>
```

**Content Element Layout**

```html
<f:layout name="Content" />
<f:render section="Main" />
```

**Wrapper Content Element**

```html
<div xmlns="http://www.w3.org/1999/xhtml" lang="en"
     xmlns:f="http://typo3.org/ns/fluid/ViewHelpers"
     xmlns:flux="http://typo3.org/ns/FluidTYPO3/Flux/ViewHelpers"
     xmlns:v="http://typo3.org/ns/FluidTYPO3/Vhs/ViewHelpers">

  <f:layout name="Content" />

  <f:section name="Configuration">
    <flux:form id="wrapper">
      <flux:form.content name="content" />
    </flux:form>
  </f:section>

  <f:section name="Preview">
    <flux:widget.grid />
  </f:section>

  <f:section name="Main">
    <section class="wrapper">
      <flux:content.render area="content" />
    </section>
  </f:section>

</div>
```

**Paragraph Content Element**

```html
<div xmlns="http://www.w3.org/1999/xhtml" lang="en"
     xmlns:f="http://typo3.org/ns/fluid/ViewHelpers"
     xmlns:flux="http://typo3.org/ns/FluidTYPO3/Flux/ViewHelpers"
     xmlns:v="http://typo3.org/ns/FluidTYPO3/Vhs/ViewHelpers">

  <f:layout name="Content" />

  <f:section name="Configuration">
    <flux:form id="paragraph">

      <!-- content sheet -->
      <flux:form.sheet name="content" label="LLL:sheets.content">
        <flux:field.text name="content.text" enableRichText="true" />
      </flux:form.sheet>

    </flux:form>
  </f:section>

  <f:section name="Preview">
    <table width="100%">
      <tr>
        <td>
          <f:format.crop maxCharacters="2000">{content.text}</f:format.crop>
        </td>
      </tr>
    </table>
  </f:section>

  <f:section name="Main">
    <div class="content-item paragraph">
      {content.text -> f:format.html()}
    </div>
  </f:section>

</div>
```

This is the way to reproduce the error: 

* Add the wrapper content element to an empty page
* Add the paragraph content element below the wrapper
* Try to drag & drop the paragraph content element inside the wrapper which doesn't work (_Image one_)
* Add another paragraph inside the wrapper
* Drag & drop the first paragraph below the added paragraph which works (_Image two_)

**Image one**
![drag_drop_error](https://cloud.githubusercontent.com/assets/157281/6963838/d781ab20-d943-11e4-8950-8b993cfda9b3.png)

**Image two**
![drag_drop_success](https://cloud.githubusercontent.com/assets/157281/6963839/d782e490-d943-11e4-9f3a-4ea31b121c7b.png)

**Comment by bjo3rnf** [comment] 2015-04-02 12:36
I can confirm this issue. What works for me is to drop the element *above* the wrapper first. After that I can drag it *into* the wrapper.

**Comment by DenisMir** [comment] 2015-04-02 12:47
@bjo3rnf I can confirm your finding. When I drag the paragraph above the wrapper and try to drag & drop it inside afterwards everything works fine.

![drag_drop_success_above](https://cloud.githubusercontent.com/assets/157281/6964191/12f6d8da-d947-11e4-859a-3169a0737b11.png)

**Comment by coding46** [comment] 2015-04-02 12:50
@DenisMir
Thanks for the example. The important part of the description is indeed the fact that it  happens if the paragraph is inserted after the wrapper at first. Now I was able to reproduce it. Same as @bjo3rnf confirmed.

**Comment by coding46** [comment] 2015-04-02 12:53
Additional information: this happens for multicolumn fluidcontent elements too but only for the first of those columns.

**Comment by jmverges** [comment] 2015-07-22 12:42
I can confirm the drag and drop issue is related with typo3pageModule.js for < 7. Using the one provided by fluidpages extension issue is solved. To maintain compatibility with both 6.2 LTS and 7 > we need to add a hook only for 6.2 LTS. However FluidTYPO3\Flux\View\PreviewView is involved in 7 >. We could use the same approach used with namespace FluidTYPO3\Fluidcontent\Backend\LegacyContentSelector

**Comment by xf-** [comment] 2015-07-25 23:25
merged and works

**Closed by xf-** 2015-07-25 23:25 UTC
