### ISSUE TITLE
Two Sites w/ different Templates are including the same Resources — unless I log into Backend

### ISSUE THREAD

**Issue by andyhausmann** [FluidTYPO3/fluidpages#265] opened 2015-07-20 10:01 UTC
Hi guys, I have a TYPO3 CMS Project containing 2 Websites w/ two slightly different designs.

In order to make those Templates available explicitly to their very own Website Tree, I decided to split the TypoScript and Templates like following:

This is a shared set of constants, being always included from all Sites:
```
plugin.tx_fluidpagestemplates.view {
	templateRootPaths.default = EXT:fluidpages_templates/Resources/Private/Templates/
	partialRootPaths.default = EXT:fluidpages_templates/Resources/Private/Partials/
	layoutRootPaths.default = EXT:fluidpages_templates/Resources/Private/Layouts/
}
```

Configuration/TypoScript/SiteOne/setup.txt (being included via Site One):
```
plugin.tx_fluidpagestemplates.view {
	templateRootPaths.site = {$plugin.tx_fluidpagestemplates.view.templateRootPaths.default}SiteOne/
	partialRootPaths.site = {$plugin.tx_fluidpagestemplates.view.partialRootPaths.default}SiteOne/
	layoutRootPaths.site = {$plugin.tx_fluidpagestemplates.view.layoutRootPaths.default}SiteOne/
}
```

Configuration/TypoScript/SiteTwo/setup.txt (being included via Site Two):
```
plugin.tx_fluidpagestemplates.view {
	templateRootPaths.site = {$plugin.tx_fluidpagestemplates.view.templateRootPaths.default}SiteTwo/
	partialRootPaths.site = {$plugin.tx_fluidpagestemplates.view.partialRootPaths.default}SiteTwo/
	layoutRootPaths.site = {$plugin.tx_fluidpagestemplates.view.layoutRootPaths.default}SiteTwo/
}
```

Both Templates are sharing various Partials and the same Layout. Within the layout I call
```
<f:render section="SiteResources" optional="1" />
```

Which is intended to include the individual Styles for each Template.

Both Templates are including the Styles like following then:
Resources/Private/Templates/SiteOne/Page/Standard.html
```
<f:section name="SiteResources">
	<v:asset.style name="styles" group="base" path="{f:uri.resource(path: 'Styles/SiteOne.css')}"/>
</f:section>
```
respectively:
Resources/Private/Templates/SiteTwo/Page/Standard.html
```
<f:section name="SiteResources">
	<v:asset.style name="styles" group="base" path="{f:uri.resource(path: 'Styles/SiteTwo.css')}"/>
</f:section>
```

The problem occuring: both websites are including the same Styles. The Style of the Website called first — I guess this refers to the first build cache for fluidpages?

If i am logged in as Backend for each Domain, I get see the correct Styles for each Website.
Any idea on how to fix this?

**Comment by andyhausmann** [comment] 2015-07-20 10:11
I've fixed it for my by just giving the resources different names:

```
<f:section name="SiteResources">
	<v:asset.style name="styles-siteone" group="base" path="{f:uri.resource(path: 'Styles/SiteOne.css')}"/>
</f:section>
```
and
```
<f:section name="SiteResources">
	<v:asset.style name="styles-sitetwo" group="base" path="{f:uri.resource(path: 'Styles/SiteTwo.css')}"/>
</f:section>
```

This solved it for me now. Should we now ignore this behavior? If you feel so, just close this one. Otherwise I would expect this is a bug, because something went wrong while caching, right?

**Comment by NamelessCoder** [comment] 2015-07-20 11:54
Hi Andy,

Thanks for the detailed description! What you experience is indeed the expected behavior of VHS assets: when an asset is cached, we identify it by its `name` property both when determining if it is already cached, and to be able to reference other assets as dependencies. This also means that if two different (in terms of *content*) assets are using the same name on the same site, then the first one to become cached will cause the second one to be "already cached" because of the name collision. However: selectively including assets on some pages only *does indeed work - as long as those assets don't use the same name*. They can belong to the same `group` just fine!

So you do want to give these a different name; maybe even give them a dedicated group so that you can target only those "site assets"; and you can use the `standalone` parameter if you don't want them to become merged, depending on how you want **browsers** to download/cache your assets. Combine these two methods and you can control both the server-side generating and local client caching of assets.

**Closed by NamelessCoder** 2015-07-20 11:54 UTC
