### ISSUE TITLE
do..while in PageService hanging server php 7.2

### ISSUE THREAD

**Issue by alexk136** [FluidTYPO3/fluidpages#390] opened 2018-10-09 14:40 UTC
Maybe it's only in my case.. a have Ngnix on Debian, with php-fpm 7.2 

loop do>while in PageService -> getPageTemplateConfiguration hanging the whole server. So i just comment it, actually li didn't see any reason to put look there, but maybe i'm wrong. 

I'm using Typo3 9.5, Flux 9.1.0 and Fluidpages 4.3.0

**Comment by alexk136** [comment] 2018-10-09 14:42
Soory forget to say, i'm using Typo3 9.5, Flux 9.1.0 and Fluidpages 4.3.0

**Comment by bpmusicDE** [comment] 2018-10-16 09:44
Same for me on a fresh xampp (win) testsystem with Typo3 9.5, Flux 9.1.0, Fluidpages 4.3.0 and VHS 5.1.0

**Comment by alexk136** [comment] 2018-10-16 10:35
Fuidpages 4.2.0 working better. I noticed that problem can come from flux page template.. if template layout not for Page.

**Comment by felixbuenemann** [comment] 2018-12-11 18:03
This bug occurs if the tx_fed_page_controller_action_sub is empty for all pages in the root line.

Eventually the `FluidTYPO3\Fluidpages\Service\PageService->getPageTemplateConfiguration()` tries to query for pages with `uid = 0` because `uid` ist set from either `pid` or `t3ver_oid` which will be `0` for pages at the root level.

Because this query never returns a `$page` the `while (null !== $page)` never abort and you have an endless loop hammering your database with queries.

The problem can not be fixed in the backend, because trying to edit the root pages with the missing `tx_fed_page_controller_action_sub` (Page Layout - subpages) would also throw an exception.

In our case the following SQL query worked around the issue:

```sql
UPDATE pages
SET tx_fed_page_controller_action_sub = tx_fed_page_controller_action
WHERE pid = 0 AND tx_fed_page_controller_action_sub = ''
```

However the proper fix would be to detect the `uid = 0` case and abort the endless loop with an error message or a fallback template.

The system in question was recently upgrade from Flux 8 to Flux 9, so it's possible the `tx_fed_page_controller_action_sub` field was optional before and is mandatory now.

**Comment by NamelessCoder** [comment] 2018-12-11 21:00
Thanks for the detective work @felixbuenemann - and you are correct, there should be a template defined as the one to use for sub-pages (though it doesn't have to be on the very root level if for example all first-level children have a setting of their own).

This is fairly high priority for us and we would greatly appreciate help in the form of a pull request to fix the endless looping. I believe a `break` when uid becomes zero should do the trick - this will then cause a more informative error to be shown (could not resolve template file "Default", if I remember the code right).

**Comment by felixbuenemann** [comment] 2018-12-12 10:35
I think the source of the problem is in [`FluidTYPO3\Fluidpages\Service\RecordService->getSingle()`](https://github.com/FluidTYPO3/flux/blob/development/Classes/Service/RecordService.php#L73) which appears to be returning `FALSE` instead of `NULL` when no record can be found, but the message signature says it should return `array|NULL`.

> [**reset()**](http://php.net/manual/en/function.reset.php) rewinds array's internal pointer to the first element and returns the value of the first array element. – Returns the value of the first array element, or **FALSE** if the array is empty.

**Comment by NamelessCoder** [comment] 2018-12-12 13:23
@felixbuenemann That sounds like at least part of the reason - that method should definitely return NULL on empty arrays. A simple ` ?: null` would do the trick.

**Comment by felixbuenemann** [comment] 2018-12-12 17:17
@NamelessCoder I submitted https://github.com/FluidTYPO3/flux/pull/1654 to fix the underlying bug in flux.

Would you like me to also submit a PR with the break-on-uid-0 logic described above?

It's still useful because it avoids a redundant SQL query and prevents the endless loop when a buggy version of flux is used.

**Comment by felixbuenemann** [comment] 2018-12-12 17:32
That would be great.

I'm also currently tracking down a similar problem on the backend in `FluidTYPO3\Flux\Provider\AbstractProvider::resolveFormClassName()` which crashes when trying to edit a page to set the sub template because it ends up passing an empty array to `ucfirst()`.

It would probably make sense to have that fix in the next release as well so people can set the missing template without editing the database by hand.

**Comment by NamelessCoder** [comment] 2018-12-12 17:37
Happy to hear that, please keep the patches coming however small they may be. Good finds and fixes so far :)

**Comment by felixbuenemann** [comment] 2018-12-12 19:55
Btw. your site is affected by this problem if queries similar to the following are shown over and over when running `SHOW FULL PROCESSLIST`, paired with high CPU load for `php-fpm` and `mysqld`:

```sql
SELECT `tx_fed_page_controller_action_sub`, `t3ver_oid`, `pid`, `uid` FROM `pages` WHERE (uid = 0) AND ((`pages`.`deleted` = 0) AND (`pages`.`hidden` = 0) AND (`pages`.`starttime` <= 1544539800) AND ((`pages`.`endtime` = 0) OR (`pages`.`endtime` > 1544539800)));
```

**Comment by NamelessCoder** [comment] 2019-03-04 14:01
Fixed via https://github.com/FluidTYPO3/fluidpages/commit/c8be6c3a5df6781c917cb334f6d3e4f28e18a1ce and https://github.com/FluidTYPO3/flux/commit/f1c2765d9a84f9e924c6b367d140061cd6c032d9.

**Closed by NamelessCoder** 2019-03-04 14:01 UTC
