### ISSUE TITLE
Subpage configuration is used instead of Page configuration with fluidpages 3.2.0

### ISSUE THREAD

**Issue by kalypsos** [FluidTYPO3/fluidpages#239] opened 2015-03-19 13:44 UTC
Upgrade to fluidpages 3.2.0

I found an error on ConfigurationService.php and resolvePageProvider function.

It return always the subpage configuration if the field tx_fed_page_controller_action is empty for the current page.

But in more case, the users edit only the root page with page layout configuration.

The children pages can't be override  the configuration.

**Comment by hirnschmalz** [comment] 2015-03-28 06:35
+1

**Comment by xf-** [comment] 2015-03-30 09:05
Contains a German description:
https://github.com/FluidTYPO3/fluidpages/issues/238

**Comment by doerler** [comment] 2015-03-30 12:57
With the bugfix 1c5b8707c45d49ed64ebd1d8dc4b18e85d460bb4 the inheritance works as excpected for the frontend. However, for the backend the problem still exists.

I think the problem could possibly have its source in the file [ConfigurationService.php](https://github.com/FluidTYPO3/fluidpages/blob/development/Classes/Service/ConfigurationService.php#L96) in function **resolvePageProvider(*$row*)**.
In there, the function **resolvePrimaryConfigurationProvider** is called with the flux configuration field name as parameter. The problem is the condition by which the field name is chosen on line 103-104. If the database field `tx_fed_page_controller_action` is empty, the main configuration field `tx_fed_page_flexform` is used, otherwise the sub configuration field `tx_fed_page_flexform_sub`.

This means that if I select the layout option **"Parent decides"** in the page settings (i.e. `tx_fed_page_controller_action` is empty), the subpage configuration field is used irrespectively of the defined main configuration.

```
102  public function resolvePageProvider($row) {
103  		$hasMainAction = FALSE === empty($row[PageProvider::FIELD_ACTION_MAIN]);
104  		$fieldName = TRUE === $hasMainAction ? PageProvider::FIELD_NAME_MAIN : PageProvider::FIELD_NAME_SUB;
105  		$provider = $this->resolvePrimaryConfigurationProvider('pages', $fieldName, $row);
106  		return $provider;
107  }
```

If I change line 103 as follows ...
```diff
- 103  $hasMainAction = FALSE === empty($row[PageProvider::FIELD_ACTION_MAIN]);
+ 103  $hasMainAction = FALSE === empty($row[PageProvider::FIELD_NAME_MAIN]);

```
... it works as desired (at least from my point of view).

Perhaps this can help you in any way.

**Comment by rzierhofer** [comment] 2015-04-15 15:03
Hi guys,
any news on this one? We are waiting desperately for a fix.
Is there any way we could support you in order to speed up things?
Thanks a lot in advance
Robert

**Comment by NamelessCoder** [comment] 2015-04-18 20:50
Hi guys - would you mind checking if branch:workbench/subprovider of EXT:fluidpages solves this problem?

https://github.com/FluidTYPO3/fluidpages/tree/workbench/subprovider

**Comment by kalypsos** [comment] 2015-04-19 10:28
@NamelessCoder. It seems branch workbench/subprovider solves this problem.

My test configuration :

TYPO3 6.2.11
Flux 7.2.0
Fluidpages 3.2
2 page layouts (Home & Standard)

**Comment by hirnschmalz** [comment] 2015-04-20 08:22
Also seems to work here

TYPO3 7.1
Flux 7.2.0

**Comment by bjo3rnf** [comment] 2015-04-20 08:40
+1 from me as well on 6.2.12 and current TER versions of the usual suspects.

**Comment by xf-** [comment] 2015-04-20 16:10
closed via https://github.com/FluidTYPO3/fluidpages/pull/252

**Closed by xf-** 2015-04-20 16:10 UTC

**Comment by rzierhofer** [comment] 2015-04-21 09:08
@NamelessCoder Thanks a lot!
You saved my week – I most def. owe you a beer or two ;)

**Comment by jenses** [comment] 2015-04-23 07:21
+1 from me, now all works fine as expected, Thanks!

**Comment by Kitzberger** [comment] 2016-06-13 11:39
It seems to me as if this was still an issue in the content wizard. The variable 'deniedContentTypes' for colPos=0 of the current page's template gets overwritten by the sub page's template.

I'm using fluid_pages 3.6.0 and flux 7.4.0

**Comment by NamelessCoder** [comment] 2016-06-13 15:14
@Kitzberger Would you mind opening a new issue about that one (and include a little bit about your template selections, e.g. are either of the fields set to "inherit" when this happens or does it happen regardless of such selections? Its smells like it but isn't the same as this issue. Thanks ;)
