### ISSUE TITLE
Page configuration: <flux:field.inline.fal> value duplicated for subpage config

### ISSUE THREAD

**Issue by cweiske** [FluidTYPO3/fluidpages#285] opened 2015-11-02 08:36 UTC
I've added [`<flux:field.inline.fal>`](https://fluidtypo3.org/viewhelpers/flux/master/Field/Inline/FalViewHelper.html) field to the page configuration.
When selecting an image for the page and saving, the same image is shown for the sub page configuration.

Screenshot:
![2015-11-02 fluidpages flux fal double](https://cloud.githubusercontent.com/assets/59036/10877285/3555efdc-8145-11e5-8577-8c01efef708f.png)

**Comment by cweiske** [comment] 2015-11-02 08:39
Seems to be a duplicate of #234, #228 and #178.

**Comment by NamelessCoder** [comment] 2015-11-08 10:53
Will close this one since it's outside our control, at least in terms of code context. What we will do is:

* Advertise this limitation a lot more; consider including it in the ViewHelper documentation itself since we now can expect that this problem will persist throughout the life of TYPO3 7 LTS.
* Point to the core issue and try to add what we can there; debugging info, ways to reproduce, suggestions for solving it and so on.
* Recommend everyone who can, that they vote for and comment on the issue to give the core team the proper indication that this is quite a serious issue which would be great to have a solution for!

And please let me know if there's something I can do to help aside from that.

**Closed by NamelessCoder** 2015-11-08 10:53 UTC
