### ISSUE TITLE
Typo3 9.5.1 + Fluidpages 4.3.0 seems to produce endless loop

### ISSUE THREAD

**Issue by ZweisteinT** [FluidTYPO3/fluidpages#397] opened 2018-11-26 00:54 UTC
Hi,
I made the following tutorial steps:

- Fresh Installation of typo3 9.5.1. (php 7.2, mysql )

-  I added the extensions vhs 5.1.0 and fluidpages 4.3.0. 

- Then i created a new root page (page->new Typo3 site) and made it visible and as root page (no content).

- Then i created a template (template->Create template for new site)(only default content)

But when i try to preview my Website (Frontend) it wont show... its just loads forever (HTTP ERROR 500). One time i had this error:

> Oops, an error occurred!
An exception occurred while executing 'SELECT `content` FROM `cf_cache_pagesection` WHERE (`identifier` = ?) AND (`expires` >= ?)' with params ["1_222419149", 1543192143]: MySQL server has gone away 

Other times I had that similar error message about cf_cache_pages. Even if i delete the db entry, it recreates it when accessing the page. it contains a blob.

1) deactivate Extension fluidpages 4.3.0, flush Caches and autoload fixed the Problem for me. It loaded Long time (on first access) but then showed hello world. Accessing afterwards was very fast.
2) Again installing Extension fluidpages 4.3.0 added the Problem again... Endless waiting time and then http error 500.

**Comment by NamelessCoder** [comment] 2018-11-26 10:47
Hi @ZweisteinT,

Can you track _where_ the loop occurs, code-wise? If you set debug context (TYPO3 application context) and enable debug output you should see the function that I assume is getting called recursively.

Please also confirm that the problem exists if you use `dev-development` branches of both Flux and Fluidpages. It's possible this problem is already solved there.

**Comment by ZweisteinT** [comment] 2018-11-26 11:19
Hi,
I just deleted all extensions and installed all from GitHub:
flux, fluidpages, vhs, builder

I think i still got that endless loop, but i am not sure. 
However, after continuing with the tutorial steps, now i have a fully working example page. The steps included:

- template includes -> fluid_styled_content

- Install builder from GitHub and use it (btw. the builder demanded me to use Vendor.name Format, even for my Emailadress and all the other fields...)

- And finally use Page->Appearance->Backend Layout->my Provider

Now when previewing i see the example page as expected.

**Comment by nyxos** [comment] 2018-12-05 16:04
Hello everyone, hi @NamelessCoder ,
I am also trying to install flux, vhs, fluidpages and builder on a fresh LTS9 installation.
And I also get the "endless loop" as soon as fluidpages is installed.
I set my website to Development Context and Debug Settings are on.
Whenever I try to view a page in the frontend, it loads and loads and eventually ends in an error 500.
Any further hints on how I can track this down ?

**Comment by apiening** [comment] 2019-02-15 21:55
I have the same issue on a fresh install of typo3 9.5.4 with composer.
I required vhs (5.1) and fluidpages (4.3) and did a database check / upgrade with the DB analyzer from maintenance. My frontend does not load anymore and CPU usage raises.
Only way I found is to disable fluidpages in the extension manager to get the frontend working.

Anyone with a hint / workaround / solution for this issue?

**Comment by moger-xx** [comment] 2019-02-27 23:01
I can confirm the behavior on TYPO3 9.5.4 / composer ddev 1.6 / mac os 10.14.3 using fluidpages 4.3.1 and Flux 9.1.0. No debug output / endless loop in frontend despite TYPO3_CONTEXT=developmen, Debug settings in localconf (FE/BE) on and system_log_level = 0. Could not get xdebug to work to find out more. 

However, the frontend works for me using the dev-development branch of flux (877f515002) after restarting ddev.  I left fluidpages on 4.3.1.

**Comment by apiening** [comment] 2019-03-04 13:36
@mneuhaus Yes you're right: It works with the dev branch for me as well.
Since this is blocking composer based installs, I would suggest to update the composer version to a more recent one where the issue is fixed.

**Comment by NamelessCoder** [comment] 2019-03-04 13:45
Fixed in https://github.com/FluidTYPO3/flux/commit/f1c2765d9a84f9e924c6b367d140061cd6c032d9, will be part of next release (of Flux).

**Closed by NamelessCoder** 2019-03-04 13:45 UTC
