### ISSUE TITLE
Referencing content items with child items bug

### ISSUE THREAD

**Issue by DenisMir** [FluidTYPO3/fluidpages#250] opened 2015-04-08 06:48 UTC
I'm working with the setup mentioned in #246 and recognized the following problem. When I'm referencing content items that contain child items in the page view with the add reference quick action icon not only the reference item gets created but also the child items get copied. Here are some screenshots documenting the problem:

_Quick action reference_
![quick_action_reference](https://cloud.githubusercontent.com/assets/157281/7040361/b0075498-ddce-11e4-9fba-63bb8b5d2bce.png) 

_Page view of a referenced item with child elements_
![page_view_reference](https://cloud.githubusercontent.com/assets/157281/7040047/385363fa-ddca-11e4-89fe-6c7faaf774d0.png)

_List view of a reference item with child elements_
![list_view_reference](https://cloud.githubusercontent.com/assets/157281/7040048/385487bc-ddca-11e4-9c9a-a5bb0c50fd79.png)

The page view also allows to edit the referenced child items without reflecting the changes back to the original item. At the moment it is better to delete all the child items in the reference to not get confused by dummy items in the list view. This bug gets even worse when you try to copy stuff from the list view to other pages. The created dummy child content elements get copied to other pages as well.

If I'm using the insert dataset content element everything works fine.

![page_view_insert_dataset](https://cloud.githubusercontent.com/assets/157281/7040342/69d42a00-ddce-11e4-9b23-e2663d7cb262.png)
![list_view_insert_dataset](https://cloud.githubusercontent.com/assets/157281/7040343/69d5dca6-ddce-11e4-9d70-5174122cf8f1.png)

**Comment by DenisMir** [comment] 2015-04-08 09:23
Ok I have updated my setup to TYPO3@6.2.11, fluidpages@3.2.0, flux@7.2.0, fluidcontent@4.2.1, vhs@2.3.0. 

I thought that the bug is now fixed but it doesn't seem so. Editing of referenced child items is no longer possible. But the dummy items are still created and listed in the list view. 

_Page view not showing the child items (correct)_
![page_view_referenced](https://cloud.githubusercontent.com/assets/157281/7042350/9290166c-dde1-11e4-89cd-2ebb672e824c.png)

_List view still shows the copied dummy items (bug)_
![list_view_referenced](https://cloud.githubusercontent.com/assets/157281/7042349/928ea1d8-dde1-11e4-96d1-980befc06cbd.png)

**Comment by xf-** [comment] 2015-07-25 23:25
confirmed

**Comment by NamelessCoder** [comment] 2015-08-02 14:14
Duplicate of https://github.com/FluidTYPO3/flux/issues/818

**Closed by NamelessCoder** 2015-08-02 14:14 UTC
